server:
  port: 9001
spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

  #序列化日期格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #打印sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

security:
  oauth2:
    client:
      # 需要和之前认证中心配置中的一样
      client-id: 123456
      client-secret: 123456
      # 获取token的地址
      access-token-uri: http://localhost:9000/oauth/token
    resource:
      id: user-web
      user-info-uri: user-info
    authorization:
      # 检查token的地址
      check-token-access: http://localhost:9000/oauth/check_token