
server:
  port: 9000

spring:
  application:
    name: oauth-server
  datasource:
    url: jdbc:mysql://192.168.10.234:3306/oauth-server?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver



